from sqlalchemy.ext.asyncio import AsyncSession

from app.models.db import ExtractionRecord
from app.models.schemas import ExtractedDocument, ExtractionResponse
from app.services.gemini_client import GeminiClient
from app.services.pdf_extractor import extract_text_from_pdf

# module-level singleton - one Gemini client shared across all requests
_gemini_client = GeminiClient()


async def run_pipeline(
    file_bytes: bytes,
    filename: str,
    db: AsyncSession,
) -> ExtractionResponse:
    """Run the full extraction pipeline: PDF bytes -> Gemini -> DB -> response."""
    text = extract_text_from_pdf(file_bytes)

    extraction: ExtractedDocument = await _gemini_client.extract_document(text)

    record = ExtractionRecord(
        filename=filename,
        document_type=extraction.document_type,
        issuer_name=extraction.issuer_name,
        recipient_name=extraction.recipient_name,
        document_date=extraction.document_date,
        document_number=extraction.document_number,
        total_amount=extraction.total_amount,
        currency=extraction.currency,
        # convert Pydantic objects to dicts for JSON column
        line_items=[item.model_dump() for item in extraction.line_items],
        summary=extraction.summary,
        raw_confidence=extraction.raw_confidence,
    )
    db.add(record)  # stages the record - not written to DB yet
    await db.commit()
    # re-reads from DB to populate id and created_at (generated by the DB)
    await db.refresh(record)

    return ExtractionResponse(
        record_id=record.id,
        filename=record.filename,
        extraction=extraction,
        created_at=record.created_at,
    )


